### ISSUE TITLE
Class DrawNodeExt: All info here  (*experimental phase*)

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#1550]
Because of possible side effects with `class DrawNode` it will be a new class/extension called `DrawNodeExt`.

FIRST:
The class `DrawNodeExt` is still in the experimental phase and may encounter bugs or stability or compatibility issues when used.

Features:
- `Individual Thickness`
```
    setDNLineWidth();
    getDNLineWidth();

    Default value: `1.0f`
```

- `Scale/Rotation/Position`
```
Scale:
    setDNScale()
    setDNScaleX()
    setDNScaleY()
Rotation:
    setDNRotation()
    getDNRotation()
    setDNCenter()
    getDNCenter()
Position:
    setDNPosition()
    getDNPosition()
```

- [ ] Add a flag setting some methods to the behaviour bevor DrawNode 2.0. #1547
- [ ] Scale drawing primitives without changing the thickness #1538
- [ ] Rotate drawing primitives around a custimized center #1537
- [ ] Add individual thickness for drawing primitives #1517
- [ ] Check the correct use of the old API vs new API on axmol: e.g: Wrong use of DrawNode::drawPolygon

Check the correct use of the old DrawNode API vs the new DrawNode API : 
see issue #1546:
Wrong use of DrawNode::drawPolygon changed to DrawNode::drawSolidRect

see list of drawPolygon calls here: #1548

**Comment by aismann** [comment]
Because of possible side effects it will be a new class/extension.
Close it here

**Comment by aismann** [comment]
closed it again (history needs a new feature issue)
